In [4]:
import pandas as pd

In [9]:
import numpy as np
import requests

In [10]:
dataset =pd.read_csv("9ef84268-d588-465a-a308-a864a43d0070.csv")

In [11]:
dataset

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price
0,Uttar Pradesh,Maharajganj,Anandnagar APMC,Wheat,Dara,FAQ,26/02/2026,2425,2625,2525.0
1,Gujarat,Ahmedabad,Sanad APMC,Wheat,Sharbati,FAQ,26/02/2026,2575,2575,2575.0
2,West Bengal,Darjeeling,Siliguri APMC,Rice,Fine(Basmati),FAQ,26/02/2026,4700,4900,4800.0
3,Tamil Nadu,Namakkal,Tiruchengode APMC,Maize,Deshi Red,Local,26/02/2026,2500,3000,2750.0
4,Tamil Nadu,Erode,Gobichettipalayam(Uzhavar Sandhai ) APMC,Maize,Deshi Red,Local,26/02/2026,3000,3500,3250.0
...,...,...,...,...,...,...,...,...,...,...
5584,Tamil Nadu,Kancheepuram,Padappai(Uzhavar Sandhai ) APMC,Mint(Pudina),Mint(Pudina),Local,26/02/2026,2000,3000,2500.0
5585,Tamil Nadu,Thiruvannamalai,Tiruvannamalai(Uzhavar Sandhai ) APMC,Rose(Local),Rose (Local),Local,26/02/2026,7000,8000,7500.0
5586,Tamil Nadu,Krishnagiri,Krishnagiri(Uzhavar Sandhai ) APMC,Rose(Local),Rose (Local),Local,26/02/2026,12000,14000,13000.0
5587,Tamil Nadu,Namakkal,Rasipuram(Uzhavar Sandhai ) APMC,Rose(Local),Rose (Local),Local,26/02/2026,12000,13000,12500.0
5588,Kerala,Alappuzha,Chengannur APMC,Elephant Yam(Suran)/Amorphophallus,Amorphophallus,FAQ,26/02/2026,3400,3800,3500.0

In [23]:
tn_data = dataset[dataset['State']=="Tamil Nadu"]

In [24]:
tn_data

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price
3,Tamil Nadu,Namakkal,Tiruchengode APMC,Maize,Deshi Red,Local,26/02/2026,2500,3000,2750.0
4,Tamil Nadu,Erode,Gobichettipalayam(Uzhavar Sandhai ) APMC,Maize,Deshi Red,Local,26/02/2026,3000,3500,3250.0
5,Tamil Nadu,Namakkal,Rasipuram(Uzhavar Sandhai ) APMC,Maize,Deshi Red,Local,26/02/2026,2500,3000,2750.0
6,Tamil Nadu,Salem,Mettur(Uzhavar Sandhai ) APMC,Maize,Deshi Red,Local,26/02/2026,2000,2500,2250.0
7,Tamil Nadu,Coimbatore,Mettupalayam(Uzhavar Sandhai ) APMC,Maize,Deshi Red,Local,26/02/2026,2500,3000,2750.0
...,...,...,...,...,...,...,...,...,...,...
5583,Tamil Nadu,Virudhunagar,Rajapalayam(Uzhavar Sandhai ) APMC,Mint(Pudina),Mint(Pudina),Local,26/02/2026,4500,5000,4750.0
5584,Tamil Nadu,Kancheepuram,Padappai(Uzhavar Sandhai ) APMC,Mint(Pudina),Mint(Pudina),Local,26/02/2026,2000,3000,2500.0
5585,Tamil Nadu,Thiruvannamalai,Tiruvannamalai(Uzhavar Sandhai ) APMC,Rose(Local),Rose (Local),Local,26/02/2026,7000,8000,7500.0
5586,Tamil Nadu,Krishnagiri,Krishnagiri(Uzhavar Sandhai ) APMC,Rose(Local),Rose (Local),Local,26/02/2026,12000,14000,13000.0
5587,Tamil Nadu,Namakkal,Rasipuram(Uzhavar Sandhai ) APMC,Rose(Local),Rose (Local),Local,26/02/2026,12000,13000,12500.0

In [25]:
print(tn_data.head())
print("Total TN rows:", len(tn_data))

        State    District                                    Market Commodity  \
3  Tamil Nadu    Namakkal                         Tiruchengode APMC     Maize
4  Tamil Nadu       Erode  Gobichettipalayam(Uzhavar Sandhai ) APMC     Maize
5  Tamil Nadu    Namakkal          Rasipuram(Uzhavar Sandhai ) APMC     Maize
6  Tamil Nadu       Salem             Mettur(Uzhavar Sandhai ) APMC     Maize
7  Tamil Nadu  Coimbatore       Mettupalayam(Uzhavar Sandhai ) APMC     Maize

     Variety  Grade Arrival_Date  Min_x0020_Price  Max_x0020_Price  \
3  Deshi Red  Local   26/02/2026             2500             3000
4  Deshi Red  Local   26/02/2026             3000             3500
5  Deshi Red  Local   26/02/2026             2500             3000
6  Deshi Red  Local   26/02/2026             2000             2500
7  Deshi Red  Local   26/02/2026             2500             3000

   Modal_x0020_Price
3             2750.0
4             3250.0
5             2750.0
6             2250.0
7             2750.0
Total TN rows: 4594

In [45]:
dataset_1 = pd.read_csv("TNweather_1.8M[1].csv")

In [46]:
dataset_1

,Unnamed: 0,temperature_2m,relative_humidity_2m,dew_point_2m,precipitation,rain,surface_pressure,cloud_cover,cloud_cover_low,wind_speed_10m,wind_direction_10m,time,city,rain_tomorrow
0,0,23.0,94.0,22.0,0.0,0.0,1004.8,88.0,29.0,8.2,23.0,2020-01-01 00:00:00,Ariyalur,1
1,1,22.8,95.0,22.0,0.0,0.0,1004.2,65.0,29.0,8.0,8.0,2020-01-01 01:00:00,Ariyalur,1
2,2,22.8,96.0,22.1,0.0,0.0,1003.5,66.0,25.0,8.3,360.0,2020-01-01 02:00:00,Ariyalur,1
3,3,22.6,97.0,22.1,0.0,0.0,1003.0,92.0,76.0,8.6,358.0,2020-01-01 03:00:00,Ariyalur,1
4,4,22.6,97.0,22.1,0.0,0.0,1003.3,100.0,100.0,9.0,360.0,2020-01-01 04:00:00,Ariyalur,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1888417,1888417,28.5,53.0,18.1,0.0,0.0,997.4,100.0,0.0,6.3,340.0,2025-08-25 07:00:00,Virudhunagar,1
1888418,1888418,31.1,42.0,16.8,0.0,0.0,997.6,99.0,0.0,5.9,337.0,2025-08-25 08:00:00,Virudhunagar,1
1888419,1888419,33.6,36.0,16.5,0.0,0.0,997.3,80.0,0.0,3.9,336.0,2025-08-25 09:00:00,Virudhunagar,1
1888420,1888420,35.5,32.0,16.5,0.0,0.0,997.0,61.0,0.0,1.6,27.0,2025-08-25 10:00:00,Virudhunagar,1
1888421,1888421,37.3,29.0,16.1,0.0,0.0,996.2,26.0,0.0,2.7,122.0,2025-08-25 11:00:00,Virudhunagar,1

In [47]:
dataset_1["State"] = "Tamil Nadu"

In [48]:
dataset_1

,Unnamed: 0,temperature_2m,relative_humidity_2m,dew_point_2m,precipitation,rain,surface_pressure,cloud_cover,cloud_cover_low,wind_speed_10m,wind_direction_10m,time,city,rain_tomorrow,State
0,0,23.0,94.0,22.0,0.0,0.0,1004.8,88.0,29.0,8.2,23.0,2020-01-01 00:00:00,Ariyalur,1,Tamil Nadu
1,1,22.8,95.0,22.0,0.0,0.0,1004.2,65.0,29.0,8.0,8.0,2020-01-01 01:00:00,Ariyalur,1,Tamil Nadu
2,2,22.8,96.0,22.1,0.0,0.0,1003.5,66.0,25.0,8.3,360.0,2020-01-01 02:00:00,Ariyalur,1,Tamil Nadu
3,3,22.6,97.0,22.1,0.0,0.0,1003.0,92.0,76.0,8.6,358.0,2020-01-01 03:00:00,Ariyalur,1,Tamil Nadu
4,4,22.6,97.0,22.1,0.0,0.0,1003.3,100.0,100.0,9.0,360.0,2020-01-01 04:00:00,Ariyalur,1,Tamil Nadu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1888417,1888417,28.5,53.0,18.1,0.0,0.0,997.4,100.0,0.0,6.3,340.0,2025-08-25 07:00:00,Virudhunagar,1,Tamil Nadu
1888418,1888418,31.1,42.0,16.8,0.0,0.0,997.6,99.0,0.0,5.9,337.0,2025-08-25 08:00:00,Virudhunagar,1,Tamil Nadu
1888419,1888419,33.6,36.0,16.5,0.0,0.0,997.3,80.0,0.0,3.9,336.0,2025-08-25 09:00:00,Virudhunagar,1,Tamil Nadu
1888420,1888420,35.5,32.0,16.5,0.0,0.0,997.0,61.0,0.0,1.6,27.0,2025-08-25 10:00:00,Virudhunagar,1,Tamil Nadu
1888421,1888421,37.3,29.0,16.1,0.0,0.0,996.2,26.0,0.0,2.7,122.0,2025-08-25 11:00:00,Virudhunagar,1,Tamil Nadu

In [49]:
dataset_1 = dataset_1.drop(columns=["Unnamed: 0"])

In [50]:
dataset_1

,temperature_2m,relative_humidity_2m,dew_point_2m,precipitation,rain,surface_pressure,cloud_cover,cloud_cover_low,wind_speed_10m,wind_direction_10m,time,city,rain_tomorrow,State
0,23.0,94.0,22.0,0.0,0.0,1004.8,88.0,29.0,8.2,23.0,2020-01-01 00:00:00,Ariyalur,1,Tamil Nadu
1,22.8,95.0,22.0,0.0,0.0,1004.2,65.0,29.0,8.0,8.0,2020-01-01 01:00:00,Ariyalur,1,Tamil Nadu
2,22.8,96.0,22.1,0.0,0.0,1003.5,66.0,25.0,8.3,360.0,2020-01-01 02:00:00,Ariyalur,1,Tamil Nadu
3,22.6,97.0,22.1,0.0,0.0,1003.0,92.0,76.0,8.6,358.0,2020-01-01 03:00:00,Ariyalur,1,Tamil Nadu
4,22.6,97.0,22.1,0.0,0.0,1003.3,100.0,100.0,9.0,360.0,2020-01-01 04:00:00,Ariyalur,1,Tamil Nadu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1888417,28.5,53.0,18.1,0.0,0.0,997.4,100.0,0.0,6.3,340.0,2025-08-25 07:00:00,Virudhunagar,1,Tamil Nadu
1888418,31.1,42.0,16.8,0.0,0.0,997.6,99.0,0.0,5.9,337.0,2025-08-25 08:00:00,Virudhunagar,1,Tamil Nadu
1888419,33.6,36.0,16.5,0.0,0.0,997.3,80.0,0.0,3.9,336.0,2025-08-25 09:00:00,Virudhunagar,1,Tamil Nadu
1888420,35.5,32.0,16.5,0.0,0.0,997.0,61.0,0.0,1.6,27.0,2025-08-25 10:00:00,Virudhunagar,1,Tamil Nadu
1888421,37.3,29.0,16.1,0.0,0.0,996.2,26.0,0.0,2.7,122.0,2025-08-25 11:00:00,Virudhunagar,1,Tamil Nadu

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

import shap

IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

In [52]:
dataset_1 = dataset_1.dropna()# drop rows with missing values 
print(data.shape)

(264576, 13)

In [57]:
def harvest_window(row):
    if row["rain_tomorrow"] > 0 or row["relative_humidity_2m"] > 85:
        return 1   # Harvest soon (0–2 days)
    else:
        return 0   # Can wait (3–5 days)

dataset_1["harvest_window"] = dataset_1.apply(harvest_window, axis=1)

#1 = Harvest soon 
#0 = can wait

In [58]:
features = [
    "temperature_2m",
    "relative_humidity_2m",
    "rain",
    "cloud_cover",
    "wind_speed_10m"
]

X = dataset_1[features]

In [59]:
X

,temperature_2m,relative_humidity_2m,rain,cloud_cover,wind_speed_10m
0,23.0,94.0,0.0,88.0,8.2
1,22.8,95.0,0.0,65.0,8.0
2,22.8,96.0,0.0,66.0,8.3
3,22.6,97.0,0.0,92.0,8.6
4,22.6,97.0,0.0,100.0,9.0
...,...,...,...,...,...
1888417,28.5,53.0,0.0,100.0,6.3
1888418,31.1,42.0,0.0,99.0,5.9
1888419,33.6,36.0,0.0,80.0,3.9
1888420,35.5,32.0,0.0,61.0,1.6
1888421,37.3,29.0,0.0,26.0,2.7

In [62]:
y_harvest = dataset_1["harvest_window"]

In [63]:
y_harvest

0          1
1          1
2          1
3          1
4          1
          ..
1888417    1
1888418    1
1888419    1
1888420    1
1888421    1
Name: harvest_window, Length: 1888422, dtype: int64

In [65]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y_harvest, test_size=0.2, random_state=42
)

In [66]:
harvest_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=8,
    random_state=42
)

harvest_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, random_state=42)

In [102]:
farmer_input = pd.DataFrame([{
    "temperature_2m": 34,
    "relative_humidity_2m": 88,
    "rain": 0,
    "cloud_cover": 75,
    "wind_speed_10m": 3
}])

In [103]:
harvest_pred = harvest_model.predict(farmer_input)[0]

if harvest_pred == 1:
    harvest_text = "Harvest in next 0–2 days"
else:
    harvest_text = "Harvest can wait 3–5 days"

In [104]:
explainer = shap.TreeExplainer(harvest_model)
shap_values = explainer.shap_values(farmer_input)

In [105]:
shap_df = pd.DataFrame({
    "Feature": farmer_input.columns,
    "Impact": shap_values[1][0]
}).sort_values(by="Impact", ascending=False)

shap_df

                Feature    Impact
1  relative_humidity_2m  0.254120
4        wind_speed_10m  0.012195
3           cloud_cover  0.004355
2                  rain -0.015759
0        temperature_2m -0.021718

In [106]:
top_features = shap_df.head(3)["Feature"].values
print(harvest_model.predict(farmer_input))
print(harvest_text)
print("💡 Why this advice?")
for f in top_features:
    if f == "relative_humidity_2m":
        print("- High humidity increases rain risk")
    elif f == "temperature_2m":
        print("- High temperature affects crop quality")
    elif f == "cloud_cover":
        print("- Cloudy weather signals possible rain")

[1]
Harvest in next 0–2 days
💡 Why this advice?
- High humidity increases rain risk
- Cloudy weather signals possible rain